board/trunk/config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :posts
    match "attach/:id" => "boards#attach", :via => [:get, :post]
  end

  namespace "m" do
    resources :boards do
      match "new_post" => "boards#new_post", :via => [:get]
      match "create_post" => "boards#create_post", :via => [:post]
      match ":id" => "boards#show_post", :via => [:get]
    end
  end

  root :to => "welcome#index"

end

board/trunk/app/models/board.rb
# -*- coding:utf-8 -*-

# Q's Web Board
# Copyright (c) 1999-2002,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# 掲示板
class Board < ActiveRecord::Base
  belongs_to :user_group
  has_many :posts

  validates_length_of :name, :within => 1..100

  before_save :normalize_before_save

  def normalize_before_save
    # TODO: 正規化
  end
end

board/trunk/app/controllers/boards_controller.rb
# -*- coding: utf-8 -*-

# Q's Web Board
# Copyright (c) 1999-2002,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# 掲示板 (PC用)。中心となるコントローラ
class BoardsController < ApplicationController
  before_filter :login_required
  before_filter :board_must_be_owned_by_ug

  verify :method => :post, :only => [ :update, :destroy ],
         :redirect_to => {:controller => "welcome", :action => "index"},
         :add_flash => {"alert" => "HTTP method incorrect."}

=begin
  def index
    @boards = Board.all
  end
=end

  
  # 投稿の表示
  def show
    @board = Board.find params[:id]
    @post = Post.new

    # 新しい順にレコードを得て、
    @posts = Post.where("board_id = ?", @board.id) \
                 .paginate(:page => params[:page], :per_page => 25) \
                 .order("created_at DESC")

    # 古い順にスレッドを作る
    rpo = []
    @posts.each do |post| rpo.unshift post end

    @threads = ThreadTree.new nil
    rpo.each do |post|
      if post.reply_to
        parent_node = @threads.find post.reply_to
        if parent_node
          parent_node << post
        else
          @threads << post
        end
      else
        @threads << post
      end
    end
  end


=begin
  # GET /boards/new
  # GET /boards/new.xml
  def new
    @board = Board.new
  end


  # POST /boards
  # POST /boards.xml
  def create
    @board = Board.new(params[:board])

    if @board.save
      redirect_to(@board, :notice => 'Board was successfully created.') 
    else
      render :action => "new" 
    end
  end
=end


  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end


  # PUT /boards/1
  # PUT /boards/1.xml
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(@board, :notice => 'Board was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /boards/1
  # DELETE /boards/1.xml
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to(boards_url) }
      format.xml  { head :ok }
    end
  end


  # 添付ファイルを表示
  def attach
    send_file "/path/to.zip", :type => "image/jpeg", :disposition => "inline"
  end
end

board/trunk/app/controllers/m/boards_controller.rb
# -*- coding: utf-8 -*-

# Q's Web Board
# Copyright (c) 1999-2002,2011 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


module M
  # mobile用の掲示板
  class BoardsController < ApplicationController

    layout "mobile"

    before_filter :login_required
    before_filter :board_must_be_owned_by_ug

    verify :method => :post, :only => [ :create_post ],
           :redirect_to => {:controller => "welcome", :action => "index"},
           :add_flash => {"alert" => "HTTP method incorrect."}


    # 投稿の一覧表示
    def show
      @board = Board.find params[:id]

      @posts = Post.paginate :page => params[:page], :per_page => 10,
                           :conditions => ["board_id = ?", @board.id],
                           :order => "created_at DESC"
    end


    # 新しいスレッド
    def new_post
      @board = Board.find params[:board_id]
      @post = Post.new :reply_to => params[:reply]
    end


    # 投稿の作成
    def create_post
      @board = Board.find params[:board_id]
      @post = Post.new params[:post]
      @post.board = @board
      @post.user = current_user

      begin
        @post.save!
      rescue ActiveRecord::RecordInvalid
        flash[:alert] = "本文がありません。"
        render :action => "new_post"
        return
      end

      flash[:notice] = "投稿しました。"
      redirect_to :action => "show", :id => @board
    end


    def show_post
      @board = Board.find params[:board_id]
      @post = Post.find params[:id]
    end
  end

end # module M

board/trunk/app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

board/trunk/app/views/boards/_post.html.erb
<% post = node.value %>

<article>
  <div style="background-color:#eeeeff">
<%= post.created_at %> <%= post.user.name %>
  </div>
  <div>
    <%= Sanitize.fragment(post.body, Sanitize::Config::RELAXED).html_safe %>
  </div>

<% if !post.attach_files.empty? %>
  <div>
<%   post.attach_files.each do |a| %>
添付: TODO::::
<%   end %>
  </div>
<% end %>
</article>

<% if !node.children.empty? %>
<blockquote style="border-left:solid 3px #eeeeee; margin-left:1.5em">
<%   node.children.each do |child| %>
<%= render :partial => "post", :locals => {:node => child} %>
<%   end %>
</blockquote>
<% end %>

<%= tag "blockquote", {:id => "reply#{post.id}", :style => "margin-left:1em"}, true %>
  <%= tag "a", {:href =>"#", :onclick =>"reply_form(#{post.id}); return false;"}, true %>返信する...</a>
</blockquote>

board/trunk/app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

board/trunk/app/views/boards/forbidden.html.erb
<% @page_title = "Forbidden" %>

<p>掲示板が見つからないか、アクセス権限がありません。

board/trunk/app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

board/trunk/app/views/boards/show.html.erb
<% @page_title = @board.name %>


<b>新しいスレッド:</b>
<%= form_for [@board, @post], :html => {:enctype => "multipart/form-data"} do |f| %>
  <%= error_messages_for :post %>

<table class="form">
  <tr>
    <td colspan="2">
      <%= f.text_area "body", :id => "editor_new", :cols => 60, :rows => 5 %>
  <tr>
    <td colspan="2" align="center">
      <input type="submit" name="submit" value="投稿" /> 
</table>
<% end %>


<script type="text/javascript">//<![CDATA[
function replace_editor(textarea_id) 
{
  CKEDITOR.replace( textarea_id, {
    height: 200,
    width: 520,
    toolbar: [
      ['Templates'],
      ['Cut', 'Copy', 'Paste', 'PasteText', '-', 'Undo', 'Redo'], 
      ['NumberedList', 'BulletedList', 'Blockquote', 'Table'], 
      ['Source', 'Preview'],
      '/',
      ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 
       '-', 'TextColor', 'BGColor'],
      ['FontSize', '-', 'RemoveFormat'],
      ['Link', 'Image', 'Smiley', 'Flash']
    ]} 
  );
}

  
function reply_form( post_id ) {
  var form = $('new_post').cloneNode( true );
  var body = form.getElementsByTagName("textarea")[0];
  body.id = "editor" + post_id;

  // 元のエディタを削除
  var e = form.getElementsByTagName("span")[0];
  e.parentNode.removeChild(e);

  form.appendChild( new Element("input", {type: "hidden", 
                                     name: "post[reply_to]", value: post_id}) );
  var e = $('reply' + post_id);
  while (e.firstChild) {
    e.removeChild(e.firstChild);
  }
  e.appendChild( form );
  replace_editor("editor" + post_id);
}

replace_editor("editor_new");
//]]>
</script>



<%= will_paginate @posts %>

<% (1 .. @threads.children.size).each do |ri| %>
<%= render :partial => "post", 
        :locals => {:node => @threads.children[@threads.children.size - ri]} %>
<% end %>


<%= will_paginate @posts %>